Update TinkoffSDK Core
Tinkoff/AcquiringSdkAndroid pull request #98
Opened 2022-07-31 22:20 UTC by Tar4s

## Аннотация
При подключенном эквайринге от Тинькофф, хочется использовать официальный фреймворк для написания сторонних клиентских приложений. В случае, когда это приложение не использует Android/iOS платформу, есть смысл отдельного использования Core-модуля. Данный SDK как раз содержит такой Core-модуль, который может доставляться maven/gradle, что подразумевает его независимое использование при написании сервисов на JVM.

## Недостатки официальной реализации Core-модуля
- В случае, когда клиентское приложение написано на Java/Kotlin для комфортного использования не хватает реализации двух функций SDK, которые все же предоставляются интерфейсом: это **Confirm** и **Cancel**
- Невозможность использовать некоторые поддерживаемые функции SDK без токена: **Charge**, **GetState**, **GetCardList**, **RemoveCard**
- Отсутствие возвращаемого URL со страницей оплаты: **PaymentURL**
- Отсутствие возможности программно задать адрес для callback-уведомлений: **NotificationURL**

## Proposal
Данные вещи были добавлены в текущем PR. Для функций, которые требуют **Token** можно точечно задать **Password** терминала, и обогатить запрос подписью, по старинке. При написании PR была использована текущая стилистика написания кода. Обратная совместимость с SDK не нарушена. _Возможность отдельного использования Core-модуля вне SDK будет крайне полезна при написании сторонних приложений, например при оплате сервисов в Telegram (!)_

**P.S. Готов к поиску компромиссов и внесения всех будущих правок**

2022-08-02 11:22 UTC, IlnarH requested changes

2022-08-02 11:22 UTC, IlnarH commented on core/src/main/java/ru/tinkoff/acquiring/sdk/network/NetworkClient.kt
> +            token += params[it]
Может, стоит использовать здесь `StringBuilder`?

2022-08-02 19:54 UTC, Tar4s commented on core/src/main/java/ru/tinkoff/acquiring/sdk/network/NetworkClient.kt
> +            token += params[it]
@IlnarH done

2022-08-03 10:23 UTC, IlnarH approved these changes

2022-08-03 11:05 UTC, IlnarH commented
Потестим и подрелизим в течение дня, появится [здесь](https://github.com/Tinkoff/AcquiringSdkAndroid/releases).

2022-08-03 11:05 UTC, merged